name: Changelogs - Daily Compile

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  compile:
    name: Compile Daily Changelogs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 25
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'
          cache: 'pip'
          cache-dependency-path: '**/changelogs/requirements.txt'
      - name: Fetch dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r **/changelogs/requirements.txt
      - name: Compile Daily Changelogs into Monthly file
        run: python tools/changelogs/compile_monthly_changelogs.py -vv
      - name: Commit and Push Compiled Changelog
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull
          git add html/changelogs
          git diff-index --quiet --cached HEAD || git commit -m "Automatic daily changelog compile [ci skip]"
          git push
