# GitHub Project board automation
# MissFox 2021
#
# Creates a new card in the project in the correct column based on draft status
name: ProjectAuto Â¦ Create Project card

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    types: [ opened ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-card-non-draft:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Create card in Open Column
        uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: Horzon PRs
          column: Open
          repo-token: ${{ secrets.TOKEN_ORG_PROJECTBOARD }}
  create-card-draft:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - name: Create card in Draft Column
        uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: Horzon PRs
          column: Draft
          repo-token: ${{ secrets.TOKEN_ORG_PROJECTBOARD }}

